export default {
  title: 'Description of the development process',
  textPrev: 'Once you decide that you are ready to cooperate - just write to me on the <a href="mailto:ulyanovs.studio@gmail.com?subject=Вопрос c ULYANOV\'S">mail</a> or in any of the <a href="#links">social networks</a>. Next, we will hold a briefing (meeting) on the main points of the project and draw up a TOR (if you do not already have one). After the brief, a prepayment is determined, on the basis of which the next stage begins - projecting.',
  textProjecting: 'In the projecting process, essential and functional site maps are compiled, reflecting the development process. Based on the maps, the time required for development is determined and the project budget is estimated. If there are no contradictions, then the next stage draws all the prototypes of the site, including the visualization and placement of elements on the page and their special dynamic changes. Prototypes are coordinated and proceed to the next stage:',
  textDesign: 'In the design process, the style of the site is determined. The main colors and typography are selected, suitable icons are selected or individual drawn, taking into account the emotional message. Designed by the UI Kit of the main elements of the site, as well as drawing layouts of pages. A grid is used, which will be used for layout. The animation is modeled. We agree.',
  textPage_making: 'After the design occurs, the development environment and the project structure are set up, the necessary use of technologies is determined. The layout is carried out in accordance with the draft layouts, adaptation for mobile devices. The code is tested in various browsers (the latest browser releases, including IE11, if necessary), as well as on different platforms. The transitions and states of interactive elements are animated.',
  textFrontend: 'The final stage configures the change and dynamic appearance of elements, the rendering features of the page and the relationship between the server and browser logic of the site. The project is tested for download speed, validity of the code, the functionality of the main user accounts is checked and possible bugs are fixed. The project is ready to be launched and integrated with the service for administering your site!<br><br><b>P.s</b>: If, after the delivery of the project, undetected bugs were found, then their correction is within the above budget and with the highest priority.<br><br><br>Still think? Then it\'s time to write me a <a href="mailto:ulyanovs.studio@gmail.com?subject=Вопрос c ULYANOV\'S">mail</a>, or in any of the social networks:',
  projecting:'Projecting',
  design:'Design',
  page_making:'Page making',
  frontend:'Fronted'
}